name: world-of-wisdom

configs:
  client-config.yaml:
    file: ./client/configs/config.yaml
  server-config.yaml:
    file: ./server/configs/config.yaml
secrets:
  client-config.secret.yaml:
    file: ./client/configs/config.dcompose.yaml
  server-config.secret.yaml:
    file: ./server/configs/config.dcompose.yaml


services:

  server:
    build:
      pull: true
      target: main
      context: ./server
      args:
        BUILD_ENV: ${BUILD_ENV:-UNKNOWN}
        BUILD_GIT_SHOW_VERSION: ${BUILD_GIT_SHOW_VERSION:-UNKNOWN}
    environment:
      ENV: ${ENV:-PROD}
      LOG_LEVE: INFO
      SERVER___ADDRESS: 0.0.0.0:1234
      SERVER___POW__ZERO_BITS_COUNT: 5
    ports: [ "127.0.0.1:1234:1234" ]
    configs: [ { source: server-config.yaml, target: /wrkdir/config.yaml }]
    secrets: [ { source: server-config.secret.yaml, target: /wrkdir/config.secret.yaml }]
    command: "./config.yaml+./config.secret.yaml"

  client:
    build:
      pull: true
      target: main
      context: ./client
      additional_contexts:
        server: ./server
      args:
        BUILD_ENV: ${BUILD_ENV:-UNKNOWN}
        BUILD_GIT_SHOW_VERSION: ${BUILD_GIT_SHOW_VERSION:-UNKNOWN}
    environment:
      ENV: ${ENV:-UNKNOWN}
      LOG_LEVEL: INFO
      SERVER_ADDRESS: server:1234
      POW_MAX_ATTEMPTS: 0
    configs: [ { source: client-config.yaml, target: /wrkdir/config.yaml }]
    secrets: [ { source: client-config.secret.yaml, target: /wrkdir/config.secret.yaml }]
    command: "./config.yaml+./config.secret.yaml"
    depends_on:
      server:
        condition: service_started


networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ${COMPOSE_PROJECT_NAME}
